//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Routes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Routes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Routes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baños.
        /// </summary>
        internal static string anchorBaño {
            get {
                return ResourceManager.GetString("anchorBaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocinas.
        /// </summary>
        internal static string anchorCocinas {
            get {
                return ResourceManager.GetString("anchorCocinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conocenos.
        /// </summary>
        internal static string anchorConocenos {
            get {
                return ResourceManager.GetString("anchorConocenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string anchorContacto {
            get {
                return ResourceManager.GetString("anchorContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        internal static string anchorDetalles {
            get {
                return ResourceManager.GetString("anchorDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachada.
        /// </summary>
        internal static string anchorFachada {
            get {
                return ResourceManager.GetString("anchorFachada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string anchorHome {
            get {
                return ResourceManager.GetString("anchorHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interiores.
        /// </summary>
        internal static string anchorInteriores {
            get {
                return ResourceManager.GetString("anchorInteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos.
        /// </summary>
        internal static string anchorNuestrosTrabajos {
            get {
                return ResourceManager.GetString("anchorNuestrosTrabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela.
        /// </summary>
        internal static string anchorParcela {
            get {
                return ResourceManager.GetString("anchorParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        internal static string anchorPresupuesto {
            get {
                return ResourceManager.GetString("anchorPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quienes Somos?.
        /// </summary>
        internal static string anchorQuienSomos {
            get {
                return ResourceManager.GetString("anchorQuienSomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vea nuestro video de presentación.
        /// </summary>
        internal static string anchorVideo {
            get {
                return ResourceManager.GetString("anchorVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baños.
        /// </summary>
        internal static string headingBaño {
            get {
                return ResourceManager.GetString("headingBaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocinas.
        /// </summary>
        internal static string headingCocinas {
            get {
                return ResourceManager.GetString("headingCocinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        internal static string headingDetalles {
            get {
                return ResourceManager.GetString("headingDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachadas.
        /// </summary>
        internal static string headingFachada {
            get {
                return ResourceManager.GetString("headingFachada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interiores.
        /// </summary>
        internal static string headingInteriores {
            get {
                return ResourceManager.GetString("headingInteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros clientes.
        /// </summary>
        internal static string headingNuestrosClientes {
            get {
                return ResourceManager.GetString("headingNuestrosClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcelas.
        /// </summary>
        internal static string headingParcela {
            get {
                return ResourceManager.GetString("headingParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quienes Somos.
        /// </summary>
        internal static string headingQuienSomos {
            get {
                return ResourceManager.GetString("headingQuienSomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Promocional.
        /// </summary>
        internal static string headingVideoPromocional {
            get {
                return ResourceManager.GetString("headingVideoPromocional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descriptcio nbaños.
        /// </summary>
        internal static string metaBaños {
            get {
                return ResourceManager.GetString("metaBaños", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripción cocinas.
        /// </summary>
        internal static string metaCocinas {
            get {
                return ResourceManager.GetString("metaCocinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conocesnos descripcion.
        /// </summary>
        internal static string metaConocenos {
            get {
                return ResourceManager.GetString("metaConocenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacto descripcion.
        /// </summary>
        internal static string metaContacto {
            get {
                return ResourceManager.GetString("metaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion detalles.
        /// </summary>
        internal static string metaDetalles {
            get {
                return ResourceManager.GetString("metaDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion fachada.
        /// </summary>
        internal static string metaFachada {
            get {
                return ResourceManager.GetString("metaFachada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home description.
        /// </summary>
        internal static string metaHome {
            get {
                return ResourceManager.GetString("metaHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion interiores.
        /// </summary>
        internal static string metaInteriores {
            get {
                return ResourceManager.GetString("metaInteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuestro trabajos descripcion.
        /// </summary>
        internal static string metaNuestroTrabajo {
            get {
                return ResourceManager.GetString("metaNuestroTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion Parcelsa.
        /// </summary>
        internal static string metaParcela {
            get {
                return ResourceManager.GetString("metaParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to presupuestos descripcionS.
        /// </summary>
        internal static string metaPresupuesto {
            get {
                return ResourceManager.GetString("metaPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos - Baños  |  JMHermanos.
        /// </summary>
        internal static string titleBaño {
            get {
                return ResourceManager.GetString("titleBaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos - Cocinas  |  JMHermanos.
        /// </summary>
        internal static string titleCocinas {
            get {
                return ResourceManager.GetString("titleCocinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactar Para Reforma  |  JMHermanos.
        /// </summary>
        internal static string titleContact {
            get {
                return ResourceManager.GetString("titleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos - Detalles  |  JMHermanos.
        /// </summary>
        internal static string titleDetalles {
            get {
                return ResourceManager.GetString("titleDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos - Fachadas  |  JMHermanos.
        /// </summary>
        internal static string titleFachadas {
            get {
                return ResourceManager.GetString("titleFachadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home  |  JMHermanos.
        /// </summary>
        internal static string titleHome {
            get {
                return ResourceManager.GetString("titleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos - Interiores  |  JMHermanos.
        /// </summary>
        internal static string titleInteriores {
            get {
                return ResourceManager.GetString("titleInteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos - Parcelas  |  JMHermanos.
        /// </summary>
        internal static string titleParcela {
            get {
                return ResourceManager.GetString("titleParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu Presupuesto  |  JMHermanos.
        /// </summary>
        internal static string titlePresupuesto {
            get {
                return ResourceManager.GetString("titlePresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos  |  JMHermanos.
        /// </summary>
        internal static string titleTrabajos {
            get {
                return ResourceManager.GetString("titleTrabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baño.
        /// </summary>
        internal static string urlBaño {
            get {
                return ResourceManager.GetString("urlBaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocina.
        /// </summary>
        internal static string urlCocinas {
            get {
                return ResourceManager.GetString("urlCocinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conocenos.
        /// </summary>
        internal static string urlConocenos {
            get {
                return ResourceManager.GetString("urlConocenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactar-Para-Reforma.
        /// </summary>
        internal static string urlContacto {
            get {
                return ResourceManager.GetString("urlContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        internal static string urlDetalles {
            get {
                return ResourceManager.GetString("urlDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachada.
        /// </summary>
        internal static string urlFachadas {
            get {
                return ResourceManager.GetString("urlFachadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string urlHome {
            get {
                return ResourceManager.GetString("urlHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interiores.
        /// </summary>
        internal static string urlInteriores {
            get {
                return ResourceManager.GetString("urlInteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela.
        /// </summary>
        internal static string urlParcela {
            get {
                return ResourceManager.GetString("urlParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu-Presupuesto.
        /// </summary>
        internal static string urlPresupuesto {
            get {
                return ResourceManager.GetString("urlPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #quienSomos.
        /// </summary>
        internal static string urlQuienSomos {
            get {
                return ResourceManager.GetString("urlQuienSomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros-Trabajos.
        /// </summary>
        internal static string urlTrabajos {
            get {
                return ResourceManager.GetString("urlTrabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #video.
        /// </summary>
        internal static string urlVideo {
            get {
                return ResourceManager.GetString("urlVideo", resourceCulture);
            }
        }
    }
}
