//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmBotonesLinksText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmBotonesLinksText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SmBotonesLinksText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baños.
        /// </summary>
        internal static string headingBaño {
            get {
                return ResourceManager.GetString("headingBaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocinas.
        /// </summary>
        internal static string headingCocinas {
            get {
                return ResourceManager.GetString("headingCocinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        internal static string headingDetalles {
            get {
                return ResourceManager.GetString("headingDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fachada.
        /// </summary>
        internal static string headingFachada {
            get {
                return ResourceManager.GetString("headingFachada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interiores.
        /// </summary>
        internal static string headingInteriores {
            get {
                return ResourceManager.GetString("headingInteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela.
        /// </summary>
        internal static string headingParcela {
            get {
                return ResourceManager.GetString("headingParcela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string menuContacto {
            get {
                return ResourceManager.GetString("menuContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Trabajos.
        /// </summary>
        internal static string menuNuestroTrabajo {
            get {
                return ResourceManager.GetString("menuNuestroTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        internal static string menuPresupuesto {
            get {
                return ResourceManager.GetString("menuPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string menuPrincipal {
            get {
                return ResourceManager.GetString("menuPrincipal", resourceCulture);
            }
        }
    }
}
